export enum HttpErrorCode {
  BAD_REQUEST = "ERR_BAD_REQUEST",
  UNAUTHORIZED = "ERR_UNAUTHORIZED",
  FORBIDDEN = "ERR_FORBIDDEN_ACCESS",
  NOT_FOUND = "ERR_NOT_FOUND",
  INTERNAL = "ERR_INTERAL_SERVER",
}
